# Site settings
title: "Jay Hennig, Ph.D."
description: "Jay Hennig, Ph.D. - computational neuroscientist"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jay Hennig"
resume_title:                   ""
resume_header_intro: "<p>Hi! I am a postdoc in neural computation and machine learning at Carnegie Mellon University, advised by <a href=\"https://users.ece.cmu.edu/~byronyu/\">Byron Yu</a> and <a href=\"http://www.cnbc.cmu.edu/~schase/index.php\">Steve Chase</a>. I'm interested in using techniques from statistics and machine learning to understand how populations of neurons interact to perceive the world and drive behavior.</p>"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       false
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_papers:          true
resume_section_posters:         false
resume_section_software:        false
resume_section_teaching:        false
resume_section_talks:           false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_email:                 "jhennig@andrew.cmu.edu"
  resume_github_url:            "https://github.com/mobeets"
  resume_scholar_url:           "https://scholar.google.com/citations?user=Tyl65TEAAAAJ&hl=en"
  resume_twitter_url:           "https://twitter.com/jehosafet"
#   resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
#   resume_linkedin_url:          ""
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://mobeets.github.io/"
#   resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
